export const PROJECTS = [
  {
    id: "tictactoe",
    titleKey: "tictactoe-title",
    image: "/assets/tictactoe.png",
    featureKeys: [
      "feature-useState",
      "feature-useEffect",
      "feature-custom-hooks",
      "feature-localStorage",
      "feature-css-modules",
      "feature-other",
      "feature-other",
    ],
    route: "/tic-tac-toe",
  },
  {
    id: "poke-collection",
    titleKey: "poke-collection-title",
    image: "/assets/poke-collection.png",
    featureKeys: [
      "feature-useState",
      "feature-useEffect",
      "feature-custom-hooks",
      "feature-localStorage",
      "feature-css-modules",
      "feature-other",
      "feature-other",
    ],
    route: "/poke-collection",
  },
  {
    id: "wordle",
    titleKey: "wordle-title",
    image: "/assets/wordle.png",
    featureKeys: [
      "feature-useState",
      "feature-useEffect",
      "feature-custom-hooks",
      "feature-localStorage",
      "feature-css-modules",
      "feature-other",
      "feature-other",
    ],
    route: "/wordle",
  },
  {
    id: "video-feed",
    titleKey: "video-feed-title",
    image: "/assets/video-feed.png",
    featureKeys: [
      "feature-useState",
      "feature-useEffect",
      "feature-custom-hooks",
      "feature-localStorage",
      "feature-css-modules",
      "feature-other",
      "feature-other",
    ],
    route: "/video-feed",
  },
] as const;
