export const PROJECTS = [
  {
    id: "tictactoe",
    titleKey: "project-tictactoe-title",
    image: "/assets/tictactoe.png",
    link: "/tic-tac-toe",
    features: [
      "feature-useState",
      "feature-useEffect",
      "feature-customHooks",
      "feature-localStorage",
      "feature-cssModules",
      "feature-otherFeature",
      "feature-otherFeature",
    ],
  },
  {
    id: "poke-collection",
    titleKey: "project-poke-title",
    image: "/assets/poke-collection.png",
    features: [
      "feature-useState",
      "feature-useEffect",
      "feature-customHooks",
      "feature-localStorage",
      "feature-cssModules",
      "feature-otherFeature",
      "feature-otherFeature",
    ],
  },
  {
    id: "wordle",
    titleKey: "project-wordle-title",
    image: "/assets/wordle.png",
    features: [
      "feature-useState",
      "feature-useEffect",
      "feature-customHooks",
      "feature-localStorage",
      "feature-cssModules",
      "feature-otherFeature",
      "feature-otherFeature",
    ],
  },
  {
    id: "video-feed",
    titleKey: "project-video-title",
    image: "/assets/video-feed.png",
    features: [
      "feature-useState",
      "feature-useEffect",
      "feature-customHooks",
      "feature-localStorage",
      "feature-cssModules",
      "feature-otherFeature",
      "feature-otherFeature",
    ],
  },
] as const;

